<?php
$data = array (
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '热点',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => '131',
    'level' => 0,
    'id' => '3',
    'name' => '热点',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '母婴护肤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '113',
    'name' => '母婴护肤',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '童车',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '童车',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '尿裤',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '139',
    'name' => '尿裤',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '玩具',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '玩具',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '童装',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '童装',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '孕婴奶粉',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '141',
    'name' => '孕婴奶粉',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '孕婴洗护',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '孕婴洗护',
  ),
  402 => 
  array (
    'cat_id' => '402',
    'cat_name' => '童床',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '402',
    'name' => '童床',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '养生保健',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '111',
    'name' => '养生保健',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '老年保健品',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '老年保健品',
  ),
  410 => 
  array (
    'cat_id' => '410',
    'cat_name' => '老人坐便器',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '410',
    'name' => '老人坐便器',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '老年服装',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '126',
    'name' => '老年服装',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '按摩保健',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '130',
    'name' => '按摩保健',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '日常用品',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '日常用品',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '康复理疗',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '131',
    'name' => '康复理疗',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '老人手机',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '老人手机',
  ),
  358 => 
  array (
    'cat_id' => '358',
    'cat_name' => '老人视听器',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '358',
    'name' => '老人视听器',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '老年车',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '125',
    'name' => '老年车',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '生鲜蔬菜',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '生鲜蔬菜',
  ),
  409 => 
  array (
    'cat_id' => '409',
    'cat_name' => '富硒蔬菜',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '409',
    'name' => '富硒蔬菜',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '水果批发',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '水果批发',
  ),
  356 => 
  array (
    'cat_id' => '356',
    'cat_name' => '蔬菜批发',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '356',
    'name' => '蔬菜批发',
  ),
  397 => 
  array (
    'cat_id' => '397',
    'cat_name' => '沂蒙特产',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '397',
    'name' => '沂蒙特产',
  ),
  403 => 
  array (
    'cat_id' => '403',
    'cat_name' => '胜亲大礼包',
    'measure_unit' => '',
    'parent_id' => '397',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '403',
    'name' => '胜亲大礼包',
  ),
  414 => 
  array (
    'cat_id' => '414',
    'cat_name' => '杏鲍菇',
    'measure_unit' => '',
    'parent_id' => '397',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '414',
    'name' => '杏鲍菇',
  ),
  398 => 
  array (
    'cat_id' => '398',
    'cat_name' => '沂蒙红嫂',
    'measure_unit' => '',
    'parent_id' => '397',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '398',
    'name' => '沂蒙红嫂',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '家居家电',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '家居家电',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '厨具',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '123',
    'name' => '厨具',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '家纺',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '灯具',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '家装建材',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '家装建材',
  ),
  411 => 
  array (
    'cat_id' => '411',
    'cat_name' => '家电',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '411',
    'name' => '家电',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '家具',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '生活用品',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '生活用品',
  ),
  386 => 
  array (
    'cat_id' => '386',
    'cat_name' => '保洁机器',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '386',
    'name' => '保洁机器',
  ),
  389 => 
  array (
    'cat_id' => '389',
    'cat_name' => '推车',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '389',
    'name' => '推车',
  ),
  390 => 
  array (
    'cat_id' => '390',
    'cat_name' => '工具',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '390',
    'name' => '工具',
  ),
  399 => 
  array (
    'cat_id' => '399',
    'cat_name' => '保洁毛巾',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '399',
    'name' => '保洁毛巾',
  ),
  388 => 
  array (
    'cat_id' => '388',
    'cat_name' => '拖把',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '388',
    'name' => '拖把',
  ),
  387 => 
  array (
    'cat_id' => '387',
    'cat_name' => '洗洁剂',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '387',
    'name' => '洗洁剂',
  ),
  391 => 
  array (
    'cat_id' => '391',
    'cat_name' => '机器',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '391',
    'name' => '机器',
  ),
  412 => 
  array (
    'cat_id' => '412',
    'cat_name' => '酒水饮料',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '412',
    'name' => '酒水饮料',
  ),
  413 => 
  array (
    'cat_id' => '413',
    'cat_name' => '茶水',
    'measure_unit' => '',
    'parent_id' => '412',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '413',
    'name' => '茶水',
  ),
  416 => 
  array (
    'cat_id' => '416',
    'cat_name' => '酒水',
    'measure_unit' => '',
    'parent_id' => '412',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '416',
    'name' => '酒水',
  ),
  417 => 
  array (
    'cat_id' => '417',
    'cat_name' => '饮料',
    'measure_unit' => '',
    'parent_id' => '412',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '417',
    'name' => '饮料',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '搞笑',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => '31',
    'level' => 0,
    'id' => '1',
    'name' => '搞笑',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '品牌保姆',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '品牌保姆',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '8h',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '20',
    'name' => '8h',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '钟点工',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '21',
    'name' => '钟点工',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '24h',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '17',
    'name' => '24h',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '保洁',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '18',
    'name' => '保洁',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '品牌月嫂',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '品牌月嫂',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '高级月嫂',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '高级月嫂',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '金牌月嫂',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '26',
    'name' => '金牌月嫂',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '中级月嫂',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '中级月嫂',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '初级月嫂',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '25',
    'name' => '初级月嫂',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '品牌护工',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => '品牌护工',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '钟点工',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '54',
    'name' => '钟点工',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '护理员',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '51',
    'name' => '护理员',
  ),
  385 => 
  array (
    'cat_id' => '385',
    'cat_name' => '专业修理',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '385',
    'name' => '专业修理',
  ),
  384 => 
  array (
    'cat_id' => '384',
    'cat_name' => '清洗保洁',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '384',
    'name' => '清洗保洁',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '健康',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => '7',
    'level' => 0,
    'id' => '2',
    'name' => '健康',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '旅游养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '58',
    'name' => '旅游养老',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '居家养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '居家养老',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '61',
    'name' => '连衣裙',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '其他养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '其他养老',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '社会义工',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => '社会义工',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '性感睡衣',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '性感睡衣',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '女士内裤',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '女士内裤',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '夏季睡衣',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '夏季睡衣',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '机构养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '机构养老',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '社区养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '社区养老',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'POLO衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => 'POLO衫',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '生活',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => '6',
    'level' => 0,
    'id' => '4',
    'name' => '生活',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '在线报名',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '146',
    'name' => '在线报名',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '培训科目',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '144',
    'name' => '培训科目',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '月嫂',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '150',
    'name' => '月嫂',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '家政服务员',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '152',
    'name' => '家政服务员',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '养老护理师',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '148',
    'name' => '养老护理师',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '催乳师',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => '催乳师',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '人才招聘',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '145',
    'name' => '人才招聘',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '教育',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '教育',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '房产中介',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '179',
    'name' => '房产中介',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => '买房',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '195',
    'name' => '买房',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => '卖房',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '198',
    'name' => '卖房',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '180',
    'name' => '厨房电器',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => '五金家装',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '182',
    'name' => '五金家装',
  ),
  218 => 
  array (
    'cat_id' => '218',
    'cat_name' => '家具五金',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '218',
    'name' => '家具五金',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => '电动工具',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '215',
    'name' => '电动工具',
  ),
  219 => 
  array (
    'cat_id' => '219',
    'cat_name' => '电工电料',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '219',
    'name' => '电工电料',
  ),
  216 => 
  array (
    'cat_id' => '216',
    'cat_name' => '手动工具',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '216',
    'name' => '手动工具',
  ),
  220 => 
  array (
    'cat_id' => '220',
    'cat_name' => '监控安防',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '220',
    'name' => '监控安防',
  ),
  217 => 
  array (
    'cat_id' => '217',
    'cat_name' => '厨卫五金',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '217',
    'name' => '厨卫五金',
  ),
  178 => 
  array (
    'cat_id' => '178',
    'cat_name' => '保险代理',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '178',
    'name' => '保险代理',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => '少儿险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '187',
    'name' => '少儿险',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => '车险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '184',
    'name' => '车险',
  ),
  185 => 
  array (
    'cat_id' => '185',
    'cat_name' => '意外险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '185',
    'name' => '意外险',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => '投资分红险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '186',
    'name' => '投资分红险',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => '养老险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '183',
    'name' => '养老险',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '情感',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '6',
    'has_children' => '7',
    'goods_num' => '5',
    'level' => 0,
    'id' => '6',
    'name' => '情感',
  ),
  307 => 
  array (
    'cat_id' => '307',
    'cat_name' => '社区理发',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '307',
    'name' => '社区理发',
  ),
  308 => 
  array (
    'cat_id' => '308',
    'cat_name' => '社区开锁',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '308',
    'name' => '社区开锁',
  ),
  383 => 
  array (
    'cat_id' => '383',
    'cat_name' => '便民服务',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '383',
    'name' => '便民服务',
  ),
  401 => 
  array (
    'cat_id' => '401',
    'cat_name' => '社区推拿',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '401',
    'name' => '社区推拿',
  ),
  310 => 
  array (
    'cat_id' => '310',
    'cat_name' => '保险超市',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 6,
    'level' => 1,
    'id' => '310',
    'name' => '保险超市',
  ),
  348 => 
  array (
    'cat_id' => '348',
    'cat_name' => '养老险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '348',
    'name' => '养老险',
  ),
  345 => 
  array (
    'cat_id' => '345',
    'cat_name' => '少儿险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '345',
    'name' => '少儿险',
  ),
  342 => 
  array (
    'cat_id' => '342',
    'cat_name' => '投资分红险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '342',
    'name' => '投资分红险',
  ),
  349 => 
  array (
    'cat_id' => '349',
    'cat_name' => '医疗险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '349',
    'name' => '医疗险',
  ),
  346 => 
  array (
    'cat_id' => '346',
    'cat_name' => '理财险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '346',
    'name' => '理财险',
  ),
  343 => 
  array (
    'cat_id' => '343',
    'cat_name' => '寿险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '343',
    'name' => '寿险',
  ),
  347 => 
  array (
    'cat_id' => '347',
    'cat_name' => '健康险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '347',
    'name' => '健康险',
  ),
  344 => 
  array (
    'cat_id' => '344',
    'cat_name' => '车险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '344',
    'name' => '车险',
  ),
  306 => 
  array (
    'cat_id' => '306',
    'cat_name' => '房产中介',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '306',
    'name' => '房产中介',
  ),
  313 => 
  array (
    'cat_id' => '313',
    'cat_name' => '租房',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '313',
    'name' => '租房',
  ),
  316 => 
  array (
    'cat_id' => '316',
    'cat_name' => '卖房',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '316',
    'name' => '卖房',
  ),
  319 => 
  array (
    'cat_id' => '319',
    'cat_name' => '买房',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '319',
    'name' => '买房',
  ),
  311 => 
  array (
    'cat_id' => '311',
    'cat_name' => '社区门诊',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '311',
    'name' => '社区门诊',
  ),
  353 => 
  array (
    'cat_id' => '353',
    'cat_name' => '专家',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '353',
    'name' => '专家',
  ),
  354 => 
  array (
    'cat_id' => '354',
    'cat_name' => '社区医生',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '354',
    'name' => '社区医生',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '酒类饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '7',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '酒类饮料',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => '饮料饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '273',
    'name' => '饮料饮品',
  ),
  291 => 
  array (
    'cat_id' => '291',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '291',
    'name' => '碳酸饮料',
  ),
  294 => 
  array (
    'cat_id' => '294',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '294',
    'name' => '酸奶',
  ),
  295 => 
  array (
    'cat_id' => '295',
    'cat_name' => '风味奶',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '295',
    'name' => '风味奶',
  ),
  289 => 
  array (
    'cat_id' => '289',
    'cat_name' => '果蔬汁',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '289',
    'name' => '果蔬汁',
  ),
  274 => 
  array (
    'cat_id' => '274',
    'cat_name' => '茗茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '274',
    'name' => '茗茶',
  ),
  303 => 
  array (
    'cat_id' => '303',
    'cat_name' => '花果茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '303',
    'name' => '花果茶',
  ),
  300 => 
  array (
    'cat_id' => '300',
    'cat_name' => '龙井',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '300',
    'name' => '龙井',
  ),
  304 => 
  array (
    'cat_id' => '304',
    'cat_name' => '养生茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '304',
    'name' => '养生茶',
  ),
  301 => 
  array (
    'cat_id' => '301',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '301',
    'name' => '绿茶',
  ),
  298 => 
  array (
    'cat_id' => '298',
    'cat_name' => '铁观音',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '298',
    'name' => '铁观音',
  ),
  305 => 
  array (
    'cat_id' => '305',
    'cat_name' => '其他茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '305',
    'name' => '其他茶',
  ),
  302 => 
  array (
    'cat_id' => '302',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '302',
    'name' => '红茶',
  ),
  299 => 
  array (
    'cat_id' => '299',
    'cat_name' => '普洱',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '299',
    'name' => '普洱',
  ),
  271 => 
  array (
    'cat_id' => '271',
    'cat_name' => '酒水',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '271',
    'name' => '酒水',
  ),
  279 => 
  array (
    'cat_id' => '279',
    'cat_name' => '黄酒/米酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '279',
    'name' => '黄酒/米酒',
  ),
  276 => 
  array (
    'cat_id' => '276',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '276',
    'name' => '白酒',
  ),
  280 => 
  array (
    'cat_id' => '280',
    'cat_name' => '养生酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '280',
    'name' => '养生酒',
  ),
  277 => 
  array (
    'cat_id' => '277',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '277',
    'name' => '啤酒',
  ),
  281 => 
  array (
    'cat_id' => '281',
    'cat_name' => '预调酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '281',
    'name' => '预调酒',
  ),
  278 => 
  array (
    'cat_id' => '278',
    'cat_name' => '葡萄酒/果酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '278',
    'name' => '葡萄酒/果酒',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => '冲调饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '272',
    'name' => '冲调饮品',
  ),
  285 => 
  array (
    'cat_id' => '285',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '285',
    'name' => '茶叶',
  ),
  286 => 
  array (
    'cat_id' => '286',
    'cat_name' => '奶茶',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '286',
    'name' => '奶茶',
  ),
  288 => 
  array (
    'cat_id' => '288',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '288',
    'name' => '咖啡',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '8',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '母婴用品',
  ),
  225 => 
  array (
    'cat_id' => '225',
    'cat_name' => '车床/床品',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '225',
    'name' => '车床/床品',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => '儿童家具',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '260',
    'name' => '儿童家具',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => '婴儿床',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '257',
    'name' => '婴儿床',
  ),
  261 => 
  array (
    'cat_id' => '261',
    'cat_name' => '睡袋/抱被',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '261',
    'name' => '睡袋/抱被',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => '餐椅',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '258',
    'name' => '餐椅',
  ),
  255 => 
  array (
    'cat_id' => '255',
    'cat_name' => '安全座椅',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '255',
    'name' => '安全座椅',
  ),
  262 => 
  array (
    'cat_id' => '262',
    'cat_name' => '凉席/蚊帐',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '262',
    'name' => '凉席/蚊帐',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => '三轮车',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '259',
    'name' => '三轮车',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => '手推车',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '256',
    'name' => '手推车',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => '营养/辅食',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '222',
    'name' => '营养/辅食',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => '果汁/泥',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '234',
    'name' => '果汁/泥',
  ),
  238 => 
  array (
    'cat_id' => '238',
    'cat_name' => '清火开胃',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '238',
    'name' => '清火开胃',
  ),
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => '面食类',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '235',
    'name' => '面食类',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => '钙铁锌',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '239',
    'name' => '钙铁锌',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => '宝宝零食',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '236',
    'name' => '宝宝零食',
  ),
  233 => 
  array (
    'cat_id' => '233',
    'cat_name' => '米粉',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '233',
    'name' => '米粉',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => '益生菌',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '240',
    'name' => '益生菌',
  ),
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => 'DHA',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '237',
    'name' => 'DHA',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => '孕妈专区',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '226',
    'name' => '孕妈专区',
  ),
  266 => 
  array (
    'cat_id' => '266',
    'cat_name' => '腰凳',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '266',
    'name' => '腰凳',
  ),
  263 => 
  array (
    'cat_id' => '263',
    'cat_name' => '孕妇裙',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '263',
    'name' => '孕妇裙',
  ),
  270 => 
  array (
    'cat_id' => '270',
    'cat_name' => '孕妇内裤',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '270',
    'name' => '孕妇内裤',
  ),
  267 => 
  array (
    'cat_id' => '267',
    'cat_name' => '妈咪包',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '267',
    'name' => '妈咪包',
  ),
  264 => 
  array (
    'cat_id' => '264',
    'cat_name' => '打底裤',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '264',
    'name' => '打底裤',
  ),
  268 => 
  array (
    'cat_id' => '268',
    'cat_name' => '收腹带',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '268',
    'name' => '收腹带',
  ),
  265 => 
  array (
    'cat_id' => '265',
    'cat_name' => '防辐射服',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '265',
    'name' => '防辐射服',
  ),
  269 => 
  array (
    'cat_id' => '269',
    'cat_name' => '哺乳文胸',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '269',
    'name' => '哺乳文胸',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => '孕婴洗护',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '223',
    'name' => '孕婴洗护',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => '孕妇护肤',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '247',
    'name' => '孕妇护肤',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => '防蚊/驱蚊',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '244',
    'name' => '防蚊/驱蚊',
  ),
  241 => 
  array (
    'cat_id' => '241',
    'cat_name' => '洗衣液/皂',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '241',
    'name' => '洗衣液/皂',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => '爽身粉',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '245',
    'name' => '爽身粉',
  ),
  242 => 
  array (
    'cat_id' => '242',
    'cat_name' => '宝宝沐浴',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '242',
    'name' => '宝宝沐浴',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => '奶瓶清洗',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '246',
    'name' => '奶瓶清洗',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => '儿童防晒',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '243',
    'name' => '儿童防晒',
  ),
  224 => 
  array (
    'cat_id' => '224',
    'cat_name' => '喂养用品',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '224',
    'name' => '喂养用品',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => '浴室用品',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '250',
    'name' => '浴室用品',
  ),
  254 => 
  array (
    'cat_id' => '254',
    'cat_name' => '防溢乳垫',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '254',
    'name' => '防溢乳垫',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => '水壶/水杯',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '251',
    'name' => '水壶/水杯',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => '奶嘴奶瓶',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '248',
    'name' => '奶嘴奶瓶',
  ),
  252 => 
  array (
    'cat_id' => '252',
    'cat_name' => '吸奶器',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '252',
    'name' => '吸奶器',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => '驱蚊用品',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '249',
    'name' => '驱蚊用品',
  ),
  253 => 
  array (
    'cat_id' => '253',
    'cat_name' => '理发器',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '253',
    'name' => '理发器',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => '孕婴奶粉',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '221',
    'name' => '孕婴奶粉',
  ),
  231 => 
  array (
    'cat_id' => '231',
    'cat_name' => '2段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '231',
    'name' => '2段',
  ),
  228 => 
  array (
    'cat_id' => '228',
    'cat_name' => '孕妈奶粉',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '228',
    'name' => '孕妈奶粉',
  ),
  232 => 
  array (
    'cat_id' => '232',
    'cat_name' => '3段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '232',
    'name' => '3段',
  ),
  229 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'pre段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '229',
    'name' => 'pre段',
  ),
  230 => 
  array (
    'cat_id' => '230',
    'cat_name' => '1段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '230',
    'name' => '1段',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => '特配奶粉',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '227',
    'name' => '特配奶粉',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '胜亲金融',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '3',
    'goods_num' => '5',
    'level' => 0,
    'id' => '10',
    'name' => '胜亲金融',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '投资',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '投资',
  ),
  415 => 
  array (
    'cat_id' => '415',
    'cat_name' => '会员卡',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '415',
    'name' => '会员卡',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '保险',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '保险',
  ),
);
?>