<?php
$data = array (
  0 => 
  array (
    'cat_id' => '3',
    'cat_name' => '热点',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => '131',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '搞笑',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => '31',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '健康',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => '7',
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '生活',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => '6',
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => '教育',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => '情感',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '6',
    'has_children' => '7',
    'goods_num' => '5',
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => '酒类饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '7',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '8',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '8',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '10',
    'cat_name' => '胜亲金融',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '3',
    'goods_num' => '5',
  ),
  9 => 
  array (
    'cat_id' => '14',
    'cat_name' => '品牌保姆',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '13',
    'cat_name' => '品牌月嫂',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '12',
    'cat_name' => '品牌护工',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '385',
    'cat_name' => '专业修理',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '384',
    'cat_name' => '清洗保洁',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '58',
    'cat_name' => '旅游养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '55',
    'cat_name' => '居家养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '59',
    'cat_name' => '其他养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '56',
    'cat_name' => '社会义工',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '60',
    'cat_name' => '机构养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '57',
    'cat_name' => '社区养老',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '113',
    'cat_name' => '母婴护肤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '111',
    'cat_name' => '养生保健',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '112',
    'cat_name' => '生鲜蔬菜',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '397',
    'cat_name' => '沂蒙特产',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '110',
    'cat_name' => '家居家电',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '386',
    'cat_name' => '保洁机器',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '412',
    'cat_name' => '酒水饮料',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '146',
    'cat_name' => '在线报名',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '144',
    'cat_name' => '培训科目',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '145',
    'cat_name' => '人才招聘',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '179',
    'cat_name' => '房产中介',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '180',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '182',
    'cat_name' => '五金家装',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '178',
    'cat_name' => '保险代理',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '307',
    'cat_name' => '社区理发',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '308',
    'cat_name' => '社区开锁',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '383',
    'cat_name' => '便民服务',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '401',
    'cat_name' => '社区推拿',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '310',
    'cat_name' => '保险超市',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 6,
  ),
  39 => 
  array (
    'cat_id' => '306',
    'cat_name' => '房产中介',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '311',
    'cat_name' => '社区门诊',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '273',
    'cat_name' => '饮料饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '274',
    'cat_name' => '茗茶',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '271',
    'cat_name' => '酒水',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '272',
    'cat_name' => '冲调饮品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '225',
    'cat_name' => '车床/床品',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '222',
    'cat_name' => '营养/辅食',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '226',
    'cat_name' => '孕妈专区',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '223',
    'cat_name' => '孕婴洗护',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '224',
    'cat_name' => '喂养用品',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '221',
    'cat_name' => '孕婴奶粉',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '42',
    'cat_name' => '投资',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '415',
    'cat_name' => '会员卡',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '45',
    'cat_name' => '保险',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '钟点工',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '51',
    'cat_name' => '护理员',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '29',
    'cat_name' => '高级月嫂',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '26',
    'cat_name' => '金牌月嫂',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '28',
    'cat_name' => '中级月嫂',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '25',
    'cat_name' => '初级月嫂',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '20',
    'cat_name' => '8h',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '21',
    'cat_name' => '钟点工',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '17',
    'cat_name' => '24h',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '18',
    'cat_name' => '保洁',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '61',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '55',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '75',
    'cat_name' => '性感睡衣',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '72',
    'cat_name' => '女士内裤',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '74',
    'cat_name' => '夏季睡衣',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'POLO衫',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '123',
    'cat_name' => '厨具',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '120',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '124',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '121',
    'cat_name' => '家装建材',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '411',
    'cat_name' => '家电',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '122',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '119',
    'cat_name' => '生活用品',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '129',
    'cat_name' => '老年保健品',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '410',
    'cat_name' => '老人坐便器',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '126',
    'cat_name' => '老年服装',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '130',
    'cat_name' => '按摩保健',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '127',
    'cat_name' => '日常用品',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '131',
    'cat_name' => '康复理疗',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '128',
    'cat_name' => '老人手机',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '358',
    'cat_name' => '老人视听器',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '125',
    'cat_name' => '老年车',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '409',
    'cat_name' => '富硒蔬菜',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '134',
    'cat_name' => '水果批发',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '356',
    'cat_name' => '蔬菜批发',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '143',
    'cat_name' => '童车',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '139',
    'cat_name' => '尿裤',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '140',
    'cat_name' => '玩具',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '136',
    'cat_name' => '童装',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  92 => 
  array (
    'cat_id' => '141',
    'cat_name' => '孕婴奶粉',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '137',
    'cat_name' => '孕婴洗护',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '402',
    'cat_name' => '童床',
    'measure_unit' => '',
    'parent_id' => '113',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '150',
    'cat_name' => '月嫂',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '152',
    'cat_name' => '家政服务员',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '148',
    'cat_name' => '养老护理师',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '149',
    'cat_name' => '催乳师',
    'measure_unit' => '',
    'parent_id' => '144',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '187',
    'cat_name' => '少儿险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '184',
    'cat_name' => '车险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '185',
    'cat_name' => '意外险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '186',
    'cat_name' => '投资分红险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '183',
    'cat_name' => '养老险',
    'measure_unit' => '',
    'parent_id' => '178',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '195',
    'cat_name' => '买房',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '198',
    'cat_name' => '卖房',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '218',
    'cat_name' => '家具五金',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '215',
    'cat_name' => '电动工具',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '219',
    'cat_name' => '电工电料',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '216',
    'cat_name' => '手动工具',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '220',
    'cat_name' => '监控安防',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '217',
    'cat_name' => '厨卫五金',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  112 => 
  array (
    'cat_id' => '231',
    'cat_name' => '2段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  113 => 
  array (
    'cat_id' => '228',
    'cat_name' => '孕妈奶粉',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  114 => 
  array (
    'cat_id' => '232',
    'cat_name' => '3段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'pre段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '230',
    'cat_name' => '1段',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '227',
    'cat_name' => '特配奶粉',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '234',
    'cat_name' => '果汁/泥',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '238',
    'cat_name' => '清火开胃',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '235',
    'cat_name' => '面食类',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '239',
    'cat_name' => '钙铁锌',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  122 => 
  array (
    'cat_id' => '236',
    'cat_name' => '宝宝零食',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '233',
    'cat_name' => '米粉',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  124 => 
  array (
    'cat_id' => '240',
    'cat_name' => '益生菌',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  125 => 
  array (
    'cat_id' => '237',
    'cat_name' => 'DHA',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '247',
    'cat_name' => '孕妇护肤',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '244',
    'cat_name' => '防蚊/驱蚊',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '241',
    'cat_name' => '洗衣液/皂',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '245',
    'cat_name' => '爽身粉',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '242',
    'cat_name' => '宝宝沐浴',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '246',
    'cat_name' => '奶瓶清洗',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '243',
    'cat_name' => '儿童防晒',
    'measure_unit' => '',
    'parent_id' => '223',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  133 => 
  array (
    'cat_id' => '250',
    'cat_name' => '浴室用品',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  134 => 
  array (
    'cat_id' => '254',
    'cat_name' => '防溢乳垫',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '251',
    'cat_name' => '水壶/水杯',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '248',
    'cat_name' => '奶嘴奶瓶',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '252',
    'cat_name' => '吸奶器',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '249',
    'cat_name' => '驱蚊用品',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  139 => 
  array (
    'cat_id' => '253',
    'cat_name' => '理发器',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '260',
    'cat_name' => '儿童家具',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  141 => 
  array (
    'cat_id' => '257',
    'cat_name' => '婴儿床',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  142 => 
  array (
    'cat_id' => '261',
    'cat_name' => '睡袋/抱被',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '258',
    'cat_name' => '餐椅',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '255',
    'cat_name' => '安全座椅',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '262',
    'cat_name' => '凉席/蚊帐',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '259',
    'cat_name' => '三轮车',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '256',
    'cat_name' => '手推车',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '266',
    'cat_name' => '腰凳',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  149 => 
  array (
    'cat_id' => '263',
    'cat_name' => '孕妇裙',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  150 => 
  array (
    'cat_id' => '270',
    'cat_name' => '孕妇内裤',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  151 => 
  array (
    'cat_id' => '267',
    'cat_name' => '妈咪包',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '264',
    'cat_name' => '打底裤',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '268',
    'cat_name' => '收腹带',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '265',
    'cat_name' => '防辐射服',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '269',
    'cat_name' => '哺乳文胸',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '279',
    'cat_name' => '黄酒/米酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '276',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  158 => 
  array (
    'cat_id' => '280',
    'cat_name' => '养生酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '277',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  160 => 
  array (
    'cat_id' => '281',
    'cat_name' => '预调酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  161 => 
  array (
    'cat_id' => '278',
    'cat_name' => '葡萄酒/果酒',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  162 => 
  array (
    'cat_id' => '285',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '286',
    'cat_name' => '奶茶',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '288',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '291',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '294',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '295',
    'cat_name' => '风味奶',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  168 => 
  array (
    'cat_id' => '289',
    'cat_name' => '果蔬汁',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '303',
    'cat_name' => '花果茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '300',
    'cat_name' => '龙井',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '304',
    'cat_name' => '养生茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '301',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  173 => 
  array (
    'cat_id' => '298',
    'cat_name' => '铁观音',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  174 => 
  array (
    'cat_id' => '305',
    'cat_name' => '其他茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '302',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '299',
    'cat_name' => '普洱',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  177 => 
  array (
    'cat_id' => '313',
    'cat_name' => '租房',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '316',
    'cat_name' => '卖房',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '319',
    'cat_name' => '买房',
    'measure_unit' => '',
    'parent_id' => '306',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '348',
    'cat_name' => '养老险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '345',
    'cat_name' => '少儿险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '342',
    'cat_name' => '投资分红险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '349',
    'cat_name' => '医疗险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  184 => 
  array (
    'cat_id' => '346',
    'cat_name' => '理财险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  185 => 
  array (
    'cat_id' => '343',
    'cat_name' => '寿险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  186 => 
  array (
    'cat_id' => '347',
    'cat_name' => '健康险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  187 => 
  array (
    'cat_id' => '344',
    'cat_name' => '车险',
    'measure_unit' => '',
    'parent_id' => '310',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  188 => 
  array (
    'cat_id' => '353',
    'cat_name' => '专家',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  189 => 
  array (
    'cat_id' => '354',
    'cat_name' => '社区医生',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  190 => 
  array (
    'cat_id' => '389',
    'cat_name' => '推车',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  191 => 
  array (
    'cat_id' => '390',
    'cat_name' => '工具',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  192 => 
  array (
    'cat_id' => '399',
    'cat_name' => '保洁毛巾',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  193 => 
  array (
    'cat_id' => '388',
    'cat_name' => '拖把',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  194 => 
  array (
    'cat_id' => '387',
    'cat_name' => '洗洁剂',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  195 => 
  array (
    'cat_id' => '391',
    'cat_name' => '机器',
    'measure_unit' => '',
    'parent_id' => '386',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  196 => 
  array (
    'cat_id' => '403',
    'cat_name' => '胜亲大礼包',
    'measure_unit' => '',
    'parent_id' => '397',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  197 => 
  array (
    'cat_id' => '414',
    'cat_name' => '杏鲍菇',
    'measure_unit' => '',
    'parent_id' => '397',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  198 => 
  array (
    'cat_id' => '398',
    'cat_name' => '沂蒙红嫂',
    'measure_unit' => '',
    'parent_id' => '397',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  199 => 
  array (
    'cat_id' => '413',
    'cat_name' => '茶水',
    'measure_unit' => '',
    'parent_id' => '412',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  200 => 
  array (
    'cat_id' => '416',
    'cat_name' => '酒水',
    'measure_unit' => '',
    'parent_id' => '412',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  201 => 
  array (
    'cat_id' => '417',
    'cat_name' => '饮料',
    'measure_unit' => '',
    'parent_id' => '412',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>